export const productsList = [
    {
        id: 1,
        name: 'Мобільний телефон Samsung Galaxy S25 Ultra',
        seller: 'Rozetka',
        producer: 'Samsung',
        memory: '12/512GB',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507063004.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/507062959.jpg',
        ],
        priceNew: 63999,
        priceOld: 67999,
        availability: 'Передзамовлення',
    },
    {
        id: 2,
        name: 'Мобільний телефон Apple iPhone 16 Pro',
        seller: 'XXX',
        producer: 'Apple',
        memory: '128GB',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886414.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886415.jpg',
        ],
        priceNew: 57499,
        priceOld: 60499,
        availability: 'Є в наявності',
    },
    {
        id: 3,
        name: 'Мобільний телефон Samsung Galaxy A35 5G',
        seller: 'Vylka',
        producer: 'Samsung',
        memory: '8/256GB',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/417133239.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/417133241.jpg',
        ],
        priceNew: 13799,
        priceOld: 13799,
        availability: 'Є в наявності',
    },
    {
        id: 4,
        name: 'Мобільний телефон Xiaomi Redmi Note 13',
        seller: 'Rozetka',
        producer: 'Xiaomi',
        memory: '8/256GB',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/498995616.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/396528095.jpg',
        ],
        priceNew: 7999,
        priceOld: 9999,
        availability: 'Є в наявності',
    },
    {
        id: 5,
        name: 'Мобільний телефон Samsung Galaxy S25 Plus',
        seller: 'Rozetka',
        producer: 'Samsung',
        memory: '12/512GB',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507063371.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/507063375.jpg',
        ],
        priceNew: 51999,
        priceOld: 55999,
        availability: 'Передзамовлення',
    },
    {
        id: 6,
        name: 'Мобільний телефон Apple iPhone 16 Pro',
        seller: 'Rozetka',
        producer: 'Apple',
        memory: '256GB',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886490.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886491.jpg',
        ],
        priceNew: 62499,
        priceOld: 65499,
        availability: 'Є в наявності',
    },
    {
        id: 7,
        name: 'Мобільний телефон Samsung Galaxy S25',
        seller: 'Vylka',
        producer: 'Samsung',
        memory: '12/256GB',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507072713.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/507072741.jpg',
        ],
        priceNew: 41999,
        priceOld: 43999,
        availability: 'Немає в наявності',
    },
    {
        id: 8,
        name: 'Мобільний телефон Nubia V60 Design',
        seller: 'Rozetka',
        producer: 'Nubia',
        memory: '6/256GB',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/454846722.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/449729389.jpg',
        ],
        priceNew: 5299,
        priceOld: 5599,
        availability: 'Передзамовлення',
    },
    {
        id: 9,
        name: 'Мобільний телефон Xiaomi Redmi Note 14 Pro',
        seller: 'Rozetka',
        producer: 'Xiaomi',
        memory: '8/256GB',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/505511671.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/505511672.jpg',
        ],
        priceNew: 10999,
        priceOld: 12999,
        availability: 'Є в наявності',
    },
    {
        id: 10,
        name: 'Мобільний телефон Apple iPhone 16',
        seller: 'Rozetka',
        producer: 'Apple',
        memory: '128GB',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/468887116.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468887117.jpg',
        ],
        priceNew: 44999,
        priceOld: 47999,
        availability: 'Немає в наявності',
    },
]
