export const productsList = [
    //-- phones
    {
        id: 101,
        category: 'mobile-phones',
        name: 'Phone Samsung Galaxy S25 Ultra',
        seller: 'Rozetka',
        brand: 'Samsung',
        memory: '12/512',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507063004.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/507062959.jpg',
        ],
        priceNew: 63999,
        priceOld: 67999,
        availability: 'Pre-order',
    },
    {
        id: 102,
        category: 'mobile-phones',
        name: 'Phone Apple iPhone 16 Pro',
        seller: 'XXX',
        brand: 'Apple',
        memory: '8/128',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886414.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886415.jpg',
        ],
        priceNew: 57499,
        priceOld: 60499,
        availability: 'Available',
    },
    {
        id: 103,
        category: 'mobile-phones',
        name: 'Phone Samsung Galaxy A35 5G',
        seller: 'Vylka',
        brand: 'Samsung',
        memory: '8/256',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/417133239.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/417133241.jpg',
        ],
        priceNew: 13799,
        priceOld: 13799,
        availability: 'Available',
    },
    {
        id: 104,
        category: 'mobile-phones',
        name: 'Phone Xiaomi Redmi Note 13',
        seller: 'Rozetka',
        brand: 'Xiaomi',
        memory: '8/256',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/498995616.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/396528095.jpg',
        ],
        priceNew: 7999,
        priceOld: 9999,
        availability: 'Available',
    },
    {
        id: 105,
        category: 'mobile-phones',
        name: 'Phone Samsung Galaxy S25 Plus',
        seller: 'Rozetka',
        brand: 'Samsung',
        memory: '12/512',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507063371.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/507063375.jpg',
        ],
        priceNew: 51999,
        priceOld: 55999,
        availability: 'Pre-order',
    },
    {
        id: 106,
        category: 'mobile-phones',
        name: 'Phone Apple iPhone 16 Pro',
        seller: 'Rozetka',
        brand: 'Apple',
        memory: '12/256',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886490.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468886491.jpg',
        ],
        priceNew: 62499,
        priceOld: 65499,
        availability: 'Available',
    },
    {
        id: 107,
        category: 'mobile-phones',
        name: 'Phone Samsung Galaxy S25',
        seller: 'Vylka',
        brand: 'Samsung',
        memory: '12/256',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/507072713.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/507072741.jpg',
        ],
        priceNew: 41999,
        priceOld: 43999,
        availability: 'Not available',
    },
    {
        id: 108,
        category: 'mobile-phones',
        name: 'Phone Nubia V60 Design',
        seller: 'Rozetka',
        brand: 'Nubia',
        memory: '6/256',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/454846722.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/449729389.jpg',
        ],
        priceNew: 5299,
        priceOld: 5599,
        availability: 'Pre-order',
    },
    {
        id: 109,
        category: 'mobile-phones',
        name: 'Phone Xiaomi Redmi Note 14 Pro',
        seller: 'Rozetka',
        brand: 'Xiaomi',
        memory: '8/256',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/505511671.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/505511672.jpg',
        ],
        priceNew: 10999,
        priceOld: 12999,
        availability: 'Available',
    },
    {
        id: 110,
        category: 'mobile-phones',
        name: 'Phone Apple iPhone 16',
        seller: 'Rozetka',
        brand: 'Apple',
        memory: '8/128',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/468887116.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/468887117.jpg',
        ],
        priceNew: 44999,
        priceOld: 47999,
        availability: 'Not available',
    },

    //-- Notebooks
    {
        id: 201,
        category: 'notebooks',
        name: 'Acer Aspire 5 A515-57-59VX',
        seller: 'Rozetka',
        brand: 'Acer',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/370191080.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/512064623.jpg',
        ],
        priceNew: 29999,
        priceOld: 22999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'Intel Core i5',
        amountOfRAM: '16',
    },
    {
        id: 202,
        category: 'notebooks',
        name: 'Lenovo IdeaPad Gaming 3 15ACH6',
        seller: 'Rozetka',
        brand: 'Lenovo',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/492468901.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/492468908.png',
        ],
        priceNew: 34999,
        priceOld: 28999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'AMD Ryzen 5',
        amountOfRAM: '16',
    },
    {
        id: 203,
        category: 'notebooks',
        name: 'ASUS TUF Gaming A15 FA506NC-HN068',
        seller: 'Rozetka',
        brand: 'ASUS',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/474547330.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/491435741.jpg',
        ],
        priceNew: 43999,
        priceOld: 35999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'AMD Ryzen 5',
        amountOfRAM: '16',
    },
    {
        id: 204,
        category: 'notebooks',
        name: 'Apple MacBook Air 13" M1 8/256GB',
        seller: 'Rozetka',
        brand: 'Apple',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/144249716.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/144249735.jpg',
        ],
        priceNew: 39499,
        priceOld: 36999,
        availability: 'Available',
        screenDiagonal: '13"',
        screenType: 'Retina',
        processor: 'Apple M1',
        amountOfRAM: '8',
    },
    {
        id: 205,
        category: 'notebooks',
        name: 'HP Laptop 15s-fq5032ua',
        seller: 'Rozetka',
        brand: 'HP',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/363540817.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/363540818.jpg',
        ],
        priceNew: 27999,
        priceOld: 20999,
        availability: 'Not available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'Intel Core i5',
        amountOfRAM: '16',
    },
    {
        id: 206,
        category: 'notebooks',
        name: 'Lenovo IdeaPad Slim 5 16IAH8',
        seller: 'Rozetka',
        brand: 'Lenovo',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/334492324.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/491380047.jpg',
        ],
        priceNew: 32999,
        priceOld: 26999,
        availability: 'Available',
        screenDiagonal: '16"',
        screenType: 'IPS',
        processor: 'Intel Core i5',
        amountOfRAM: '16',
    },
    {
        id: 207,
        category: 'notebooks',
        name: 'Acer Aspire 7 A715-76G-560W',
        seller: 'Rozetka',
        brand: 'Acer',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/362592851.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/503528711.jpg',
        ],
        priceNew: 37999,
        priceOld: 31999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'Intel Core i5',
        amountOfRAM: '16',
    },
    {
        id: 208,
        category: 'notebooks',
        name: 'ASUS TUF Gaming A15 FA507NVR-LP086',
        seller: 'Rozetka',
        brand: 'ASUS',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/474547330.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/491435741.jpg',
        ],
        priceNew: 49999,
        priceOld: 51999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'AMD Ryzen 7',
        amountOfRAM: '18',
    },
    {
        id: 209,
        category: 'notebooks',
        name: 'HP Laptop 15s-eq2056ua',
        seller: 'Rozetka',
        brand: 'HP',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/207458919.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/207458938.jpg',
        ],
        priceNew: 22999,
        priceOld: 17777,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'IPS',
        processor: 'AMD Ryzen 3',
        amountOfRAM: '16',
    },
    {
        id: 210,
        category: 'notebooks',
        name: 'ASUS VivoBook 15 OLED M1505YA-MA269',
        seller: 'Rozetka',
        brand: 'ASUS',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/467999360.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/467999361.jpg',
        ],
        priceNew: 34999,
        priceOld: 24999,
        availability: 'Available',
        screenDiagonal: '15.6"',
        screenType: 'OLED',
        processor: 'AMD Ryzen 5',
        amountOfRAM: '32',
    },

    //-- kettles
    {
        id: 301,
        category: 'electric-kettles',
        name: 'Electrolux E3K1-3ST',
        seller: 'Rozetka',
        brand: 'Electrolux',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/358268736.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/358268737.jpg',
        ],
        priceNew: 2199,
        priceOld: 999,
        availability: 'Available',
        power: '2400',
        volume: '1.7',
    },
    {
        id: 302,
        category: 'electric-kettles',
        name: 'Bosch MyMoment TWK1M123',
        seller: 'XXX',
        brand: 'Bosch',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/395026035.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/395026036.jpg',
        ],
        priceNew: 1799,
        priceOld: 1299,
        availability: 'Available',
        power: '2400',
        volume: '1.5',
    },
    {
        id: 303,
        category: 'electric-kettles',
        name: 'Electrolux E5K1-6AN Graphite',
        seller: 'Rozetka',
        brand: 'Electrolux',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/494570059.webp',
            'https://content1.rozetka.com.ua/goods/images/big_tile/473039970.jpg',
        ],
        priceNew: 4399,
        priceOld: 2777,
        availability: 'Available',
        power: '2400',
        volume: '2.0',
    },
    {
        id: 304,
        category: 'electric-kettles',
        name: 'Philips Viva Collection HD9352/30',
        seller: 'Rozetka',
        brand: 'Philips',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/379463349.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/379285599.jpg',
        ],
        priceNew: 2999,
        priceOld: 1999,
        availability: 'Not available',
        power: '1850',
        volume: '1.2',
    },
    {
        id: 305,
        category: 'electric-kettles',
        name: 'Tefal Glass Kettle KI605B30',
        seller: 'Rozetka',
        brand: 'Tefal',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/486473399.webp',
            'https://content.rozetka.com.ua/goods/images/big_tile/423078929.jpg',
        ],
        priceNew: 2799,
        priceOld: 1999,
        availability: 'Available',
        power: '2200',
        volume: '1.6',
    },
    {
        id: 306,
        category: 'electric-kettles',
        name: 'Bosch TWK2M161',
        seller: 'XXX',
        brand: 'Bosch',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/394805355.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/394805356.jpg',
        ],
        priceNew: 2099,
        priceOld: 1399,
        availability: 'Available',
        power: '2400',
        volume: '1.7',
    },
    {
        id: 307,
        category: 'electric-kettles',
        name: 'Philips Daily Collection HD9359/90',
        seller: 'Rozetka',
        brand: 'Philips',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/163133688.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/163133682.jpg',
        ],
        priceNew: 2899,
        priceOld: 1999,
        availability: 'Available',
        power: '1850',
        volume: '1.5',
    },
    {
        id: 308,
        category: 'electric-kettles',
        name: 'Bosch TWK3P420',
        seller: 'XXX',
        brand: 'Bosch',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/18592642.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/18592584.jpg',
        ],
        priceNew: 2399,
        priceOld: 1699,
        availability: 'Not available',
        power: '2400',
        volume: '1.8',
    },
    {
        id: 309,
        category: 'electric-kettles',
        name: 'Panasonic NC-EG3000WTS',
        seller: 'Rozetka',
        brand: 'Panasonic',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/10973871.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/10973840.jpg',
        ],
        priceNew: 4899,
        priceOld: 3599,
        availability: 'Available',
        power: '700',
        volume: '2.5',
    },
    {
        id: 310,
        category: 'electric-kettles',
        name: 'Aeno EK7S',
        seller: 'Rozetka',
        brand: 'Aeno',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/342172414.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/294301304.jpg',
        ],
        priceNew: 3799,
        priceOld: 2599,
        availability: 'Available',
        power: '2200',
        volume: '2.0',
    },
    //-- alcohol
    {
        id: 401,
        category: 'champagne-and-wine',
        name: 'Veuve Clicquot Ponsardin Brut',
        seller: 'Rozetka',
        brand: 'Veuve Clicquot',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/498025184.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/498025184.jpg',
        ],
        priceNew: 4669,
        priceOld: 4299,
        availability: 'Available',
        color: 'White',
        volume: '0.75',
    },
    {
        id: 402,
        category: 'champagne-and-wine',
        name: 'Wonderland By Minna Parikka Cava Brut Rose',
        seller: 'Rozetka',
        brand: 'Minna Parikka',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/486899765.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/486899765.jpg',
        ],
        priceNew: 450,
        priceOld: 229,
        availability: 'Available',
        color: 'Pink',
        volume: '0.75',
    },
    {
        id: 403,
        category: 'champagne-and-wine',
        name: 'Casa Farive Prosecco DOC Brut',
        seller: 'Rozetka',
        brand: 'Casa Farive',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/511684463.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/509197845.jpg',
        ],
        priceNew: 500,
        priceOld: 299,
        availability: 'Not available',
        color: 'White',
        volume: '0.5',
    },
    {
        id: 404,
        category: 'champagne-and-wine',
        name: 'Astoria Prosecco Spumante DOC Rose Millesimato',
        seller: 'Rozetka',
        brand: 'Astoria',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/188847586.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/188847586.jpg',
        ],
        priceNew: 420,
        priceOld: 299,
        availability: 'Pre-order',
        color: 'Pink',
        volume: '0.75',
    },
    {
        id: 405,
        category: 'champagne-and-wine',
        name: 'Ruggeri Ladaltempo Valdobbiadene Prosecco Superiore DOCG Brut',
        seller: 'Rozetka',
        brand: 'Ruggeri',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/493055447.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/493055447.jpg',
        ],
        priceNew: 4779,
        priceOld: 3800,
        availability: 'Available',
        color: 'White',
        volume: '1.5',
    },
    {
        id: 406,
        category: 'champagne-and-wine',
        name: 'Cremant De Limoux AOP Brut Nature',
        seller: 'Rozetka',
        brand: 'Cremant De Limoux',
        img: [
            'https://content2.rozetka.com.ua/goods/images/big_tile/436059691.jpg',
            'https://content2.rozetka.com.ua/goods/images/big_tile/436059691.jpg',
        ],
        priceNew: 1300,
        priceOld: 650,
        availability: 'Available',
        color: 'White',
        volume: '0.75',
    },
    {
        id: 407,
        category: 'champagne-and-wine',
        name: 'Murviedro Cava Brut Organic Rose',
        seller: 'Rozetka',
        brand: 'Murviedro',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/486919878.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/486919878.jpg',
        ],
        priceNew: 560,
        priceOld: 339,
        availability: 'Available',
        color: 'Pink',
        volume: '0.75',
    },
    {
        id: 408,
        category: 'champagne-and-wine',
        name: 'Mondoro Asti',
        seller: 'Rozetka',
        brand: 'Mondoro',
        img: [
            'https://content1.rozetka.com.ua/goods/images/big_tile/383363733.jpg',
            'https://content1.rozetka.com.ua/goods/images/big_tile/383363733.jpg',
        ],
        priceNew: 599,
        priceOld: 429,
        availability: 'Available',
        color: 'White',
        volume: '0.5',
    },
    {
        id: 409,
        category: 'champagne-and-wine',
        name: 'ONDE Prosecco Frizzante Doc Treviso Dry',
        seller: 'Rozetka',
        brand: 'ONDE',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/490507905.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/490507905.jpg',
        ],
        priceNew: 420,
        priceOld: 259,
        availability: 'Available',
        color: 'White',
        volume: '0.75',
    },
    {
        id: 410,
        category: 'champagne-and-wine',
        name: 'Heretat el Padruell Cava Brut Nature',
        seller: 'Rozetka',
        brand: 'Heretat el Padruell',
        img: [
            'https://content.rozetka.com.ua/goods/images/big_tile/243458885.jpg',
            'https://content.rozetka.com.ua/goods/images/big_tile/243458885.jpg',
        ],
        priceNew: 400,
        priceOld: 289,
        availability: 'Available',
        color: 'White',
        volume: '0.75',
    },
]
